
CREATE TABLE public.event (
    eventid integer NOT NULL,
    title character varying(100) NOT NULL,
    startdate date NOT NULL,
    enddate date NOT NULL,
    price double precision DEFAULT 0 NOT NULL,
    attendeescount integer DEFAULT 0 NOT NULL,
    revenue double precision DEFAULT 0 NOT NULL
);


ALTER TABLE public.event OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 534235)
-- Name: Event_EventID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.event ALTER COLUMN eventid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Event_EventID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 534126)
-- Name: eventorganizer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.eventorganizer (
    userid integer NOT NULL,
    eventid integer NOT NULL
);


ALTER TABLE public.eventorganizer OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 534119)
-- Name: eventsession; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.eventsession (
    sessionid integer NOT NULL,
    title character varying(100) NOT NULL,
    description text,
    date date NOT NULL,
    location character varying(100) NOT NULL,
    online boolean NOT NULL,
    eventid integer NOT NULL
);


ALTER TABLE public.eventsession OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 534236)
-- Name: eventsession_SessionID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.eventsession ALTER COLUMN sessionid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."eventsession_SessionID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 534144)
-- Name: transaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transaction (
    transactionid integer NOT NULL,
    userid integer NOT NULL,
    fees double precision NOT NULL,
    type character varying(50) NOT NULL
);


ALTER TABLE public.transaction OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 534237)
-- Name: transaction_TransactionID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transaction ALTER COLUMN transactionid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."transaction_TransactionID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 534131)
-- Name: user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."user" (
    userid integer NOT NULL,
    name character varying(100) NOT NULL,
    email character varying(50) NOT NULL,
    password character varying(50) NOT NULL,
    balance double precision DEFAULT 0 NOT NULL,
    outstandingfees double precision DEFAULT 0 NOT NULL,
    role character varying(50) NOT NULL
);


ALTER TABLE public."user" OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 534238)
-- Name: user_UserID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."user" ALTER COLUMN userid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."user_UserID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4722 (class 2606 OID 534125)
-- Name: eventsession EventSession_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventsession
    ADD CONSTRAINT "EventSession_pkey" PRIMARY KEY (sessionid);


--
-- TOC entry 4720 (class 2606 OID 534118)
-- Name: event Event_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event
    ADD CONSTRAINT "Event_pkey" PRIMARY KEY (eventid);


--
-- TOC entry 4728 (class 2606 OID 534148)
-- Name: transaction Transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT "Transaction_pkey" PRIMARY KEY (transactionid);


--
-- TOC entry 4726 (class 2606 OID 534135)
-- Name: user User_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT "User_pkey" PRIMARY KEY (userid);


--
-- TOC entry 4723 (class 1259 OID 534154)
-- Name: fki_EventID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "fki_EventID" ON public.eventsession USING btree (eventid);


--
-- TOC entry 4724 (class 1259 OID 534141)
-- Name: fki_UserID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "fki_UserID" ON public.eventorganizer USING btree (userid);


--
-- TOC entry 4730 (class 2606 OID 534160)
-- Name: eventorganizer EventID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventorganizer
    ADD CONSTRAINT "EventID" FOREIGN KEY (eventid) REFERENCES public.event(eventid) ON UPDATE SET DEFAULT ON DELETE CASCADE NOT VALID;


--
-- TOC entry 4729 (class 2606 OID 534165)
-- Name: eventsession EventID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventsession
    ADD CONSTRAINT "EventID" FOREIGN KEY (eventid) REFERENCES public.event(eventid) ON UPDATE SET DEFAULT ON DELETE CASCADE NOT VALID;


--
-- TOC entry 4731 (class 2606 OID 534155)
-- Name: eventorganizer UserID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventorganizer
    ADD CONSTRAINT "UserID" FOREIGN KEY (userid) REFERENCES public."user"(userid) ON UPDATE SET DEFAULT ON DELETE CASCADE NOT VALID;


--
-- TOC entry 4732 (class 2606 OID 534173)
-- Name: transaction UserID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

-- ALTER TABLE ONLY public.transaction
--     ADD CONSTRAINT "UserID" FOREIGN KEY (userid) REFERENCES public."user"(userid) ON UPDATE SET DEFAULT ON DELETE CASCADE NOT VALID;

ALTER TABLE public.transaction
ADD COLUMN eventid integer NOT NULL,
ADD COLUMN paymentmethod character varying(50) NOT NULL,
ADD COLUMN status character varying(20) DEFAULT 'pending' NOT NULL;
-- Completed on 2025-04-09 04:57:49

--
-- PostgreSQL database dump complete
--



